on:
  push:
    # Sequence of patterns matched against refs/heads
    #branches-ignore:
    #  - 'master'  # Ignore push events to branches matching master
    #  - 'develop' # Ignore push events to branches matching develop

    paths:
      - 'docs/**'

jobs:
  links:
    name: Test Links
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: build
      - shell: bash
        run: ls -la build

      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -d build -r *

      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}