name: Markdown

on:
  push:
    # Sequence of patterns matched against refs/heads
    #branches-ignore:
    #  - 'master'  # Ignore push events to branches matching master
    #  - 'develop' # Ignore push events to branches matching develop

    paths:
      - 'docs/**'

jobs:
  Remark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: remark
      id: remark
      uses: ocular-d/action-remark@0.0.9
      with:
        check_dir: 'docs'